global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'shortkenny'
    static_configs:
      - targets: ['app:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

